/* eslint-disable @typescript-eslint/no-explicit-any */
import { appointments, doctors, doctorLeaves, employees, equipment, faqs, galleryImages, maintenanceLogs, medicines, patients, reviews, schedules, services } from "@/db/schema";

/** Whitelist of admin-manageable collections and writable columns. */
export const resources: Record<string, { table: any; label: string; searchable: string[]; writable: string[]; required: string[]; fields: { key:string; label:string; type?:string; options?:string[]; optionLabels?:Record<string,string> }[] }> = {
  patients: { table: patients, label: "Patients", searchable: ["name","phone","email"], writable: ["name","phone","email","address","age","gender","bloodGroup","medicalInfo","dentalHistory","notes"], required: ["name","phone"], fields: [{key:"name",label:"Full name"},{key:"phone",label:"Phone"},{key:"email",label:"Email",type:"email"},{key:"age",label:"Age",type:"number"},{key:"gender",label:"Gender",type:"select",options:["","MALE","FEMALE","OTHER"]},{key:"address",label:"Address"},{key:"bloodGroup",label:"Blood group"},{key:"medicalInfo",label:"Medical information",type:"textarea"},{key:"dentalHistory",label:"Dental history",type:"textarea"},{key:"notes",label:"Notes",type:"textarea"}] },
  doctors: { table: doctors, label: "Doctors", searchable: ["name","qualification","specialization","phone","email"], writable: ["name","slug","photoUrl","qualification","specialization","experienceYears","biography","phone","email","consultationFee","order","isActive"], required: ["name","slug"], fields: [{key:"name",label:"Name"},{key:"slug",label:"Profile slug"},{key:"photoUrl",label:"Photo",type:"image"},{key:"qualification",label:"Qualification"},{key:"specialization",label:"Specialization"},{key:"experienceYears",label:"Years of experience",type:"number"},{key:"consultationFee",label:"Consultation fee",type:"number"},{key:"phone",label:"Phone"},{key:"email",label:"Email",type:"email"},{key:"biography",label:"Biography",type:"textarea"},{key:"isActive",label:"Active",type:"checkbox"}] },
  employees: { table: employees, label: "Employees", searchable: ["name","position","phone","email"], writable: ["name","photoUrl","position","phone","email","joiningDate","responsibilities","notes","isActive"], required: ["name"], fields: [{key:"name",label:"Name"},{key:"position",label:"Position"},{key:"phone",label:"Phone"},{key:"email",label:"Email",type:"email"},{key:"joiningDate",label:"Joining date",type:"date"},{key:"responsibilities",label:"Responsibilities",type:"textarea"},{key:"notes",label:"Notes",type:"textarea"},{key:"isActive",label:"Active",type:"checkbox"}] },
  services: { table: services, label: "Services", searchable: ["name","description"], writable: ["name","slug","description","price","duration","imageUrl","isFeatured","order","isActive"], required: ["name","slug"], fields: [{key:"name",label:"Name"},{key:"slug",label:"Slug"},{key:"price",label:"Price (৳)",type:"number"},{key:"duration",label:"Duration (minutes)",type:"number"},{key:"description",label:"Description",type:"textarea"},{key:"imageUrl",label:"Image",type:"image"},{key:"isFeatured",label:"Featured",type:"checkbox"},{key:"isActive",label:"Active",type:"checkbox"}] },
  medicines: { table: medicines, label: "Medicines", searchable: ["name","category","supplier"], writable: ["name","category","quantity","unit","purchasePrice","supplier","expiryDate","minStockLevel","notes"], required: ["name"], fields: [{key:"name",label:"Medicine name"},{key:"category",label:"Category"},{key:"quantity",label:"Quantity",type:"number"},{key:"unit",label:"Unit"},{key:"purchasePrice",label:"Purchase price",type:"number"},{key:"supplier",label:"Supplier"},{key:"expiryDate",label:"Expiry date",type:"date"},{key:"minStockLevel",label:"Minimum stock",type:"number"},{key:"notes",label:"Notes",type:"textarea"}] },
  equipment: { table: equipment, label: "Equipment", searchable: ["name","serialNumber","location"], writable: ["name","serialNumber","purchaseDate","purchasePrice","condition","warrantyUntil","location","lastMaintenance","nextMaintenance","status","notes"], required: ["name"], fields: [{key:"name",label:"Equipment name"},{key:"serialNumber",label:"Serial number"},{key:"condition",label:"Condition",type:"select",options:["EXCELLENT","GOOD","FAIR","NEEDS_REPAIR","OUT_OF_SERVICE"]},{key:"status",label:"Status",type:"select",options:["ACTIVE","UNDER_MAINTENANCE","RETIRED"]},{key:"location",label:"Location"},{key:"purchaseDate",label:"Purchase date",type:"date"},{key:"purchasePrice",label:"Purchase price",type:"number"},{key:"warrantyUntil",label:"Warranty until",type:"date"},{key:"lastMaintenance",label:"Last maintenance",type:"date"},{key:"nextMaintenance",label:"Next maintenance",type:"date"},{key:"notes",label:"Notes",type:"textarea"}] },
  reviews: { table: reviews, label: "Reviews", searchable: ["name","comment"], writable: ["name","rating","comment","isApproved"], required: ["name","rating","comment"], fields: [{key:"name",label:"Patient name"},{key:"rating",label:"Rating (1–5)",type:"number"},{key:"comment",label:"Review",type:"textarea"},{key:"isApproved",label:"Approved for publication",type:"checkbox"}] },
  gallery: { table: galleryImages, label: "Gallery", searchable: ["title"], writable: ["title","imageUrl","order","isPublished"], required: ["imageUrl"], fields: [{key:"title",label:"Caption"},{key:"imageUrl",label:"Image",type:"image"},{key:"order",label:"Sort order",type:"number"},{key:"isPublished",label:"Published",type:"checkbox"}] },
  faqs: { table: faqs, label: "FAQs", searchable: ["question","answer"], writable: ["question","answer","order","isActive"], required: ["question","answer"], fields: [{key:"question",label:"Question"},{key:"answer",label:"Answer",type:"textarea"},{key:"order",label:"Sort order",type:"number"},{key:"isActive",label:"Active",type:"checkbox"}] },
  appointments: { table: appointments, label: "Appointments", searchable: ["reference","status","notes"], writable: ["status","adminNote"], required: [], fields: [{key:"status",label:"Status",type:"select",options:["PENDING","CONFIRMED","COMPLETED","CANCELLED","RESCHEDULED"]},{key:"adminNote",label:"Admin note",type:"textarea"}] },
  schedules: { table: schedules, label: "Schedules", searchable: [], writable: ["doctorId","dayOfWeek","startTime","endTime","slotMinutes","isActive"], required: ["doctorId","dayOfWeek","startTime","endTime"], fields: [{key:"doctorId",label:"Doctor",type:"select",options:[]},{key:"dayOfWeek",label:"Weekday",type:"select",options:["0","1","2","3","4","5","6"],optionLabels:{"0":"Saturday","1":"Sunday","2":"Monday","3":"Tuesday","4":"Wednesday","5":"Thursday","6":"Friday"}},{key:"startTime",label:"Start time",type:"time"},{key:"endTime",label:"End time",type:"time"},{key:"slotMinutes",label:"Slot length (min)",type:"number"},{key:"isActive",label:"Active",type:"checkbox"}] },
  leaves: { table: doctorLeaves, label: "Doctor leaves", searchable: ["reason"], writable: ["doctorId","date","reason"], required: ["doctorId","date"], fields: [{key:"doctorId",label:"Doctor",type:"select",options:[]},{key:"date",label:"Unavailable date",type:"date"},{key:"reason",label:"Reason"}] },
  maintenance: { table: maintenanceLogs, label: "Maintenance logs", searchable: ["description","performedBy"], writable: ["equipmentId","date","description","cost","performedBy"], required: ["equipmentId","date"], fields: [{key:"equipmentId",label:"Equipment",type:"select",options:[]},{key:"date",label:"Date",type:"date"},{key:"description",label:"Description",type:"textarea"},{key:"cost",label:"Cost",type:"number"},{key:"performedBy",label:"Performed by"}] },
};
